### PR TITLE
Only push Date when Date is available

### LINKED ISSUE #1: Error in `extendsPage`
Getting this error trying to add the plugin to our site:

```
⠹ Initializing and preparing dataerror error in hook extendsPage from vuepress-plugin-open-graph
✖ Initializing and preparing data - failed in 9.22s
RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at Object.extendsPage [as hook] (file:///Users/forrestevans/Documents/GitHub/docs/node_modules/vuepress-plugin-open-graph/dist/server/index.js:19:62)
    at Object.process (file:///Users/forrestevans/Documents/GitHub/docs/node_modules/@vuepress/core/dist/index.js:681:37)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async createPage (file:///Users/forrestevans/Documents/GitHub/docs/node_modules/@vuepress/core/dist/index.js:568:3)
    at async Promise.all (index 296)
    at async resolveAppPages (file:///Users/forrestevans/Documents/GitHub/docs/node_modules/@vuepress/core/dist/index.js:580:17)
    at async appInit (file:///Users/forrestevans/Documents/GitHub/docs/node_modules/@vuepress/core/dist/index.js:603:15)
    at async file:///Users/forrestevans/Documents/GitHub/docs/node_modules/@vuepress/cli/dist/index.js:487:7
    at async file:///Users/forrestevans/Documents/GitHub/docs/node_modules/@vuepress/utils/dist/index.js:106:20
```

Using the latest build of `2.0.0-beta.67`

### PR DESCRIPTION
**Pull request by fdevans**
This update fixes the situation where frontmatter may exist without a date entry.  It only pushes the date if one exists.

Please include a summary of the changes.
 
- Adds validation that a date exists in frontmatter before trying to convert to string.

Fixes #1

### CODE REVIEW

File: server/index.ts [hunk 1]
```diff
@@ -33,14 +33,15 @@ export let openGraphPlugin =
...
         head.push(['meta', { property: 'og:type', content: 'article' }])
-
-        head.push([
-          'meta',
-          {
-            content: new Date(page.frontmatter.date!).toISOString(),
-            property: 'article:published_time',
-          },
-        ])
+        if (page.frontmatter.date {
```
Comment (azat-io) [inline server/index.ts]:
```suggestion
        if (page.frontmatter.date) {
```

Could you add missed `)`?

Comment (fdevans) [reply server/index.ts]: Sorry... Pushed fix.  That's what I get for trying to quick fix inside GitHub editor. :(

**Comment by azat-io** [comment]
Thanks. Released in [v1.5.1](https://github.com/azat-io/vuepress-plugin-open-graph/releases/tag/v1.5.1)
